export class ROM {
  constructor(
    public checksum: number,
    public title: string,
    public logo: Uint8Array<ArrayBuffer>,
    public manufacturerCode: Uint8Array<ArrayBuffer>,
    public newLicenseeCode: string,
    public oldLicenseeCode: string,
    public CGBFlag: number,
    public SGBFlag: number,
    public cartridgeType: string,
    public ROMSize: { value: number; size: string; numberOfROMBanks: string },
    public RAMSize: { code: number; SRAMSize: string; comment: string },
    public destinationCode: string,
    public maskROMVersionNumber: number,
    public globalChecksum: Uint8Array<ArrayBuffer>,
    public data: Uint8Array<ArrayBuffer>
  ) {}

  static async load(url: string) {
    return new Uint8Array(await (await fetch(url)).arrayBuffer());
  }

  static parse(file: Uint8Array) {
    const td = new TextDecoder();

    const checksum = file[0x014d];
    let checksum_acc = 0;
    for (let address = 0x0134; address <= 0x014c; address++) {
      checksum_acc = checksum_acc - file[address] - 1;
    }
    if ((checksum & 0xff) !== (checksum_acc & 0xff)) {
      throw new Error(`Checksum missmatch, expected ${checksum} got ${checksum_acc}`);
    }

    return new ROM(
      checksum,
      td.decode(file.slice(0x0134, 0x0143)).replace(/\0/g, ""),
      file.slice(0x0104, 0x0133),
      file.slice(0x013f, 0x0142),
      NewLicenseeCodes[String(file[0x0144]) + String(file[0x0145])],
      OldLicenseeCodes[file[0x014b]],
      file[0x0143],
      file[0x0146],
      CartridgeTypes[file[0x0147]],
      ROMSizes[file[0x0148]],
      RAMSizes[file[0x0149]],
      DestinationCodes[file[0x014a]],
      file[0x014c],
      file.slice(0x014e, 0x014f),
      file
    );
  }

  read(addr: number): number {
    return this.data[addr];
  }

  write(addr: number, value: number): void {}
}

const NewLicenseeCodes = {
  "00": "None",
  "01": "Nintendo Research & Development 1",
  "08": "Capcom",
  "13": "EA (Electronic Arts)",
  "18": "Hudson Soft",
  "19": "B-AI",
  "20": "KSS",
  "22": "Planning Office WADA",
  "24": "PCM Complete",
  "25": "San-X",
  "28": "Kemco",
  "29": "SETA Corporation",
  "30": "Viacom",
  "31": "Nintendo",
  "32": "Bandai",
  "33": "Ocean Software/Acclaim Entertainment",
  "34": "Konami",
  "35": "HectorSoft",
  "37": "Taito",
  "38": "Hudson Soft",
  "39": "Banpresto",
  "41": "Ubi Soft1",
  "42": "Atlus",
  "44": "Malibu Interactive",
  "46": "Angel",
  "47": "Bullet-Proof Software2",
  "49": "Irem",
  "50": "Absolute",
  "51": "Acclaim Entertainment",
  "52": "Activision",
  "53": "Sammy USA Corporation",
  "54": "Konami",
  "55": "Hi Tech Expressions",
  "56": "LJN",
  "57": "Matchbox",
  "58": "Mattel",
  "59": "Milton Bradley Company",
  "60": "Titus Interactive",
  "61": "Virgin Games Ltd.3",
  "64": "Lucasfilm Games4",
  "67": "Ocean Software",
  "69": "EA (Electronic Arts)",
  "70": "Infogrames5",
  "71": "Interplay Entertainment",
  "72": "Broderbund",
  "73": "Sculptured Software6",
  "75": "The Sales Curve Limited7",
  "78": "THQ",
  "79": "Accolade",
  "80": "Misawa Entertainment",
  "83": "lozc",
  "86": "Tokuma Shoten",
  "87": "Tsukuda Original",
  "91": "Chunsoft Co.8",
  "92": "Video System",
  "93": "Ocean Software/Acclaim Entertainment",
  "95": "Varie",
  "96": "Yonezawa/s'pal",
  "97": "Kaneko",
  "99": "Pack-In-Video",
  "9H": "Bottom Up",
  A4: "Konami (Yu-Gi-Oh!)",
  BL: "MTO",
  DK: "Kodansha",
} as const;

const OldLicenseeCodes = {
  0x00: "None",
  0x01: "Nintendo",
  0x08: "Capcom",
  0x09: "HOT-B",
  0x0a: "Jaleco",
  0x0b: "Coconuts Japan",
  0x0c: "Elite Systems",
  0x13: "EA (Electronic Arts)",
  0x18: "Hudson Soft",
  0x19: "ITC Entertainment",
  0x1a: "Yanoman",
  0x1d: "Japan Clary",
  0x1f: "Virgin Games Ltd.3",
  0x24: "PCM Complete",
  0x25: "San-X",
  0x28: "Kemco",
  0x29: "SETA Corporation",
  0x30: "Infogrames5",
  0x31: "Nintendo",
  0x32: "Bandai",
  0x33: "New licensee code should be used instead.",
  0x34: "Konami",
  0x35: "HectorSoft",
  0x38: "Capcom",
  0x39: "Banpresto",
  0x3c: "Entertainment Interactive (stub)",
  0x3e: "Gremlin",
  0x41: "Ubi Soft1",
  0x42: "Atlus",
  0x44: "Malibu Interactive",
  0x46: "Angel",
  0x47: "Spectrum HoloByte",
  0x49: "Irem",
  0x4a: "Virgin Games Ltd.3",
  0x4d: "Malibu Interactive",
  0x4f: "U.S. Gold",
  0x50: "Absolute",
  0x51: "Acclaim Entertainment",
  0x52: "Activision",
  0x53: "Sammy USA Corporation",
  0x54: "GameTek",
  0x55: "Park Place13",
  0x56: "LJN",
  0x57: "Matchbox",
  0x59: "Milton Bradley Company",
  0x5a: "Mindscape",
  0x5b: "Romstar",
  0x5c: "Naxat Soft14",
  0x5d: "Tradewest",
  0x60: "Titus Interactive",
  0x61: "Virgin Games Ltd.3",
  0x67: "Ocean Software",
  0x69: "EA (Electronic Arts)",
  0x6e: "Elite Systems",
  0x6f: "Electro Brain",
  0x70: "Infogrames5",
  0x71: "Interplay Entertainment",
  0x72: "Broderbund",
  0x73: "Sculptured Software6",
  0x75: "The Sales Curve Limited7",
  0x78: "THQ",
  0x79: "Accolade15",
  0x7a: "Triffix Entertainment",
  0x7c: "MicroProse",
  0x7f: "Kemco",
  0x80: "Misawa Entertainment",
  0x83: "LOZC G.",
  0x86: "Tokuma Shoten",
  0x8b: "Bullet-Proof Software2",
  0x8c: "Vic Tokai Corp.16",
  0x8e: "Ape Inc.17",
  0x8f: "I'Max18",
  0x91: "Chunsoft Co.8",
  0x92: "Video System",
  0x93: "Tsubaraya Productions",
  0x95: "Varie",
  0x96: "Yonezawa19/S'Pal",
  0x97: "Kemco",
  0x99: "Arc",
  0x9a: "Nihon Bussan",
  0x9b: "Tecmo",
  0x9c: "Imagineer",
  0x9d: "Banpresto",
  0x9f: "Nova",
  0xa1: "Hori Electric",
  0xa2: "Bandai",
  0xa4: "Konami",
  0xa6: "Kawada",
  0xa7: "Takara",
  0xa9: "Technos Japan",
  0xaa: "Broderbund",
  0xac: "Toei Animation",
  0xad: "Toho",
  0xaf: "Namco",
  0xb0: "Acclaim Entertainment",
  0xb1: "ASCII Corporation or Nexsoft",
  0xb2: "Bandai",
  0xb4: "Square Enix",
  0xb6: "HAL Laboratory",
  0xb7: "SNK",
  0xb9: "Pony Canyon",
  0xba: "Culture Brain",
  0xbb: "Sunsoft",
  0xbd: "Sony Imagesoft",
  0xbf: "Sammy Corporation",
  0xc0: "Taito",
  0xc2: "Kemco",
  0xc3: "Square",
  0xc4: "Tokuma Shoten",
  0xc5: "Data East",
  0xc6: "Tonkin House",
  0xc8: "Koei",
  0xc9: "UFL",
  0xca: "Ultra Games",
  0xcb: "VAP, Inc.",
  0xcc: "Use Corporation",
  0xcd: "Meldac",
  0xce: "Pony Canyon",
  0xcf: "Angel",
  0xd0: "Taito",
  0xd1: "SOFEL (Software Engineering Lab)",
  0xd2: "Quest",
  0xd3: "Sigma Enterprises",
  0xd4: "ASK Kodansha Co.",
  0xd6: "Naxat Soft14",
  0xd7: "Copya System",
  0xd9: "Banpresto",
  0xda: "Tomy",
  0xdb: "LJN",
  0xdd: "Nippon Computer Systems",
  0xde: "Human Ent.",
  0xdf: "Altron",
  0xe0: "Jaleco",
  0xe1: "Towa Chiki",
  0xe2: "Yutaka # Needs more info",
  0xe3: "Varie",
  0xe5: "Epoch",
  0xe7: "Athena",
  0xe8: "Asmik Ace Entertainment",
  0xe9: "Natsume",
  0xea: "King Records",
  0xeb: "Atlus",
  0xec: "Epic/Sony Records",
  0xee: "IGS",
  0xf0: "A Wave",
  0xf3: "Extreme Entertainment",
  0xff: "LJN",
} as const;

const CartridgeTypes = {
  0x00: "ROM ONLY",
  0x01: "MBC1",
  0x02: "MBC1+RAM",
  0x03: "MBC1+RAM+BATTERY",
  0x05: "MBC2",
  0x06: "MBC2+BATTERY",
  0x08: "ROM+RAM 9",
  0x09: "ROM+RAM+BATTERY 9",
  0x0b: "MMM01",
  0x0c: "MMM01+RAM",
  0x0d: "MMM01+RAM+BATTERY",
  0x0f: "MBC3+TIMER+BATTERY",
  0x10: "MBC3+TIMER+RAM+BATTERY 10",
  0x11: "MBC3",
  0x12: "MBC3+RAM 10",
  0x13: "MBC3+RAM+BATTERY 10",
  0x19: "MBC5",
  0x1a: "MBC5+RAM",
  0x1b: "MBC5+RAM+BATTERY",
  0x1c: "MBC5+RUMBLE",
  0x1d: "MBC5+RUMBLE+RAM",
  0x1e: "MBC5+RUMBLE+RAM+BATTERY",
  0x20: "MBC6",
  0x22: "MBC7+SENSOR+RUMBLE+RAM+BATTERY",
  0xfc: "POCKET CAMERA",
  0xfd: "BANDAI TAMA5",
  0xfe: "HuC3",
  0xff: "HuC1+RAM+BATTERY",
} as const;

const ROMSizes = {
  0x00: { value: 0x00, size: "32 KiB", numberOfROMBanks: "2 (no banking)" },
  0x01: { value: 0x01, size: "64 KiB", numberOfROMBanks: "4" },
  0x02: { value: 0x02, size: "128 KiB", numberOfROMBanks: "8" },
  0x03: { value: 0x03, size: "256 KiB", numberOfROMBanks: "16" },
  0x04: { value: 0x04, size: "512 KiB", numberOfROMBanks: "32" },
  0x05: { value: 0x05, size: "1 MiB", numberOfROMBanks: "64" },
  0x06: { value: 0x06, size: "2 MiB", numberOfROMBanks: "128" },
  0x07: { value: 0x07, size: "4 MiB", numberOfROMBanks: "256" },
  0x08: { value: 0x08, size: "8 MiB", numberOfROMBanks: "512" },
  0x52: { value: 0x52, size: "1.1 MiB", numberOfROMBanks: "72 11" },
  0x53: { value: 0x53, size: "1.2 MiB", numberOfROMBanks: "80 11" },
  0x54: { value: 0x54, size: "1.5 MiB", numberOfROMBanks: "96 11" },
} as const;

const RAMSizes = {
  0x00: { code: 0x00, SRAMSize: "0", comment: "No RAM" },
  0x01: { code: 0x01, SRAMSize: "-", comment: "Unused" },
  0x02: { code: 0x02, SRAMSize: "8 KiB", comment: "1 bank" },
  0x03: { code: 0x03, SRAMSize: "32 KiB", comment: "4 banks of 8 KiB each" },
  0x04: { code: 0x04, SRAMSize: "128 KiB", comment: "16 banks of 8 KiB each" },
  0x05: { code: 0x05, SRAMSize: "64 KiB", comment: "8 banks of 8 KiB each" },
} as const;

const DestinationCodes = {
  0x00: "Japan (and possibly overseas)",
  0x01: "Overseas only",
} as const;
