---
name: ci
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**.ts"
      - .github/workflows/ci.yaml
  workflow_call: null
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: yarn test:integration
